### ISSUE TITLE
fix ACE-Unload Problem with vehicles

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#10]
Tanks (an all tracked vehicles?) get damaged when unloaded.
Trucks getting unloaded inside Chopper (Tempest inside Taru)

**Comment by Frozen-byte** [comment]
further reading (german) https://armaworld.de/index.php?thread/4515-ace3-cargo-ausladeort-angeben/&postID=36508#post36508

**Comment by Frozen-byte** [comment]
[ace_modified_pdos.zip](https://github.com/OperationPandoraTrigger/OPT-Mission/files/3464434/ace_modified_pdos.zip)

Form hat zwei PBOs von ACE modifiziert damit das Ausladen von Fahrzeugen nun gefahrlos funktioniert:

- Startradius, Maximalradius und Fahrzeuggröße vergrößert.
- Damage wird nach dem Ausladen auf 0 gesetzt, damit die Engine wieder funktioniert.

Der Ursprung des Fehlers liegt aber nicht bei ACE sondern wahrscheinlich bei unseren modifizierten Fahrzeugen - da müssen wir in Ruhe nochmal genauer gucken.

**Comment by formtapez** [comment]
Patch fürs nächste ACE-Update:
[ace-patch.zip](https://github.com/OperationPandoraTrigger/OPT-Mission/files/3746441/ace-patch.zip)

**Comment by formtapez** [comment]
Pull requests bei ACE erstellt:
https://github.com/acemod/ACE3/pull/7128
https://github.com/acemod/ACE3/pull/7129
