### ISSUE TITLE
Radar für Träger

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#100]
Soll statisches Radar auf den Träger mit  Datalink.
Das die Positionen an alle Fahrzeuge übermittelt.

**Comment by Yayshan** [comment]
@GNCLORD-MDB 
Die Reichweite des Radar soll nur 5km betragen
Das Gerät darf nicht verlade fähig sein.

**Comment by GNCLORD-MDB** [comment]
Ist beides.
Hat nur 5km aktiv Radar und kann nicht verladen werden. 

@Frozen-byte 
Ja anders wäre das wohl sehr unsinnig :-)

**Comment by Frozen-byte** [comment]
Ich muss noch lernen die DoDs korrekt zu formulieren, gebt mir ein bisschen Zeit mit jedem Mal wird es besser, versprochen =P

**Comment by Yayshan** [comment]
@GNCLORD-MDB  Aktuellen PR abgelehnt, wird so nicht umgesetzt.

- Es werden die statischen Radarsysteme der jeweiligen Fraktions verwendet werden. (Encore Update)
- Maximale Radar Reichweite ist 2,5 Kilometer (Radius)
- Das Radar darf nicht verladbar sein
- Das System muss Infanterie aufdecken können

BI Wiki für Snesor Mechanic:
https://community.bistudio.com/wiki/Arma_3_Sensors_config_reference

**Comment by GNCLORD-MDB** [comment]
Kann du mir mal verraten woher das kommt und was das soll?
Wie soll und darf das nur ein Statische Radar sein.
Und @Frozen-byte sagte 5km nicht 2,5km

**Comment by Frozen-byte** [comment]
5km Durchmesser = 2.5km Radius.  Sorry habe ich vielleicht falsch formuliert.

**Comment by GNCLORD-MDB** [comment]
@Frozen-byte du macht mich fertig, du hast 5km geschrieben und es sind 5km.
Dann ändere ich das noch Ebend auf 2.5km

**Comment by Yayshan** [comment]
> Wie soll und darf das nur ein Statische Radar sein.

Weil die EL da so beschlossen hat

**Comment by GNCLORD-MDB** [comment]
Da Ding in statisch oder wie bezeichnet man etwas das sich nicht bewegen kann.

**Comment by Yayshan** [comment]
Musst du  echt alles ausdiskutieren? 
WEST soll AN/MPQ-105 Radar als Radar System auf dem Träger stehen haben
EAST soll R-750 Cronus Radar als Radar System auf dem Träger stehen haben

**Comment by GNCLORD-MDB** [comment]
Das sind alles Drohne Systeme, die Arbeiten ohne Operator nicht.
Dazu haben die nur eine 90° Winkel. 
Drittens müssen die erster in dem Mod eingebaut werden, die Flak ist da schon vorhanden und erfüllt den gleichen zweck.

**Comment by GNCLORD-MDB** [comment]
Das hatte ich alles auch schon ausgibig im Forum geschrieben.

**Comment by GNCLORD-MDB** [comment]
"Das System muss Infanterie aufdecken können" ist garn nicht möglich mit dem Arma System . 
Wenn ein muss seinen soll dann brauchen wir wieder das alte System mit einem Script. 
Und das sollte @frozen alles wissen.

**Comment by OPTManu** [comment]
>Das sind alles Drohne Systeme, die Arbeiten ohne Operator nicht.

Sobald eine KI drin sitzt arbeiten die, auch ohne externen Operator.


> Dazu haben die nur eine 45° Winkel.

Komisch, letztens hatten sie laut dir einen 90°-Winkel, was stimmt denn nun?
Ich helfe mal, nichts davon, die Radare haben einen 120°-Winkel, der über die Mod ebenso verändert werden kann wie alles andere auch.


> "Das System muss Infanterie aufdecken können" ist garn nicht möglich mit dem Arma System .

Du hast den Artikel offensichtlich nicht gelesen, denn sonst wüsstest du, dass es seit dem Sensorupdate auch visuelle Sensoren gibt, die Infanterie erkennen, wie es z.B. die Darter auf der ersten Tanoakampagne konnte. 
**Du sollst unter anderem prüfen, ob es möglich ist, diese Funktion auf die statischen Radaranlagen zu übertragen, davor wird dein PR weder von Yoshi noch von Frozen angenommen.**
Ich hoffe, es ist dir klar genug dargestellt

**Comment by GNCLORD-MDB** [comment]
Es sind 90° ein viertel vom Kreis. 
Sicher kann ich das Drohnesystem umbauen das auch 360° hat. 
Und ich bin mir eigentlich sicher das Radar nicht von beginn eingeschaltet ist bei dem Drohnesystem.

Die Frage ist warum der ganze Aufwand, das Sonderfahrzeug hat das alles jetzt schon. 
wo liegt da der mehr nutzen.

**Comment by Frozen-byte** [comment]
> wo liegt da der mehr nutzen.


Ich möchte ich es nicht provozieren. Ein **Fahrzeug** welches _nicht bewegt_ werden soll; lädt ja richtig dazu ein es doch zu schaffen.

Der Nutzen liegt zudem auch in der visuellen Eleganz.

Wir haben die Zeit und keinen wirtschaftlichen Druck.

Also mach es bitte anständig, ich möchte keine Halbherzigen und fertigen "funktioniert also schluck" Implementierungen mehr.

**Comment by GNCLORD-MDB** [comment]
Ich habe das nun noch mal ausgibig und intensiv getestet.
Obwohl ich das auch Stundenlang schon vorher gemacht habe. 

Das Drohnennsystem läuft nicht Autonom !
Alles muss vom Operator aktiviert und gesteuert werden !
Ist der Operator wieder getrennt ,hört alles auch zu arbeiten. 

Wenn es um die Optik geht werde ich nun mal versuchen das Model von der Statischen Radar auf die Flak zu ziehen. damit ihr alle ruhig schlafen könnt.

Den Inf detektor habe ich auch nach Stunden suchen in Internet hin bekommen. 
Der arbeitet nach Sicht also muss das Radar eine Sichtline dazu haben! 
Alles was zwischen dem Radar steht verdeckt dann wieder die anzeige !

**Comment by Yayshan** [comment]
> Das Drohnennsystem läuft nicht Autonom !
> Alles muss vom Operator aktiviert und gesteuert werden !

Komisch - wenn ich das Radar zusammen mit einer Sam oder was anderes platziere arbeitet es automatisch. Ohne Operator. 
siehe auch: https://www.youtube.com/watch?v=0sNSxnT7ong

**Comment by OPTManu** [comment]
> Es sind 90° ein viertel vom Kreis.
Sicher kann ich das Drohnesystem umbauen das auch 360° hat.
Und ich bin mir eigentlich sicher das Radar nicht von beginn eingeschaltet ist bei dem Drohnesystem.

https://opt4.net/userstorage/manu/Inked20200206173449_1_LI.jpg
https://opt4.net/userstorage/manu/20200206173443_1.jpg
Aufgenommen im AN/MPQ-105 Defender, das Radarsystem der NATO, im Kronos der CSAT siehts auch so aus. Gerade im zweiten Bild sieht man ziemlich eindeutig, dass das keine 90° nur sind.


> Ich habe das nun noch mal ausgibig und intensiv getestet.
Obwohl ich das auch Stundenlang schon vorher gemacht habe.
>Das Drohnennsystem läuft nicht Autonom !
Alles muss vom Operator aktiviert und gesteuert werden !
Ist der Operator wieder getrennt ,hört alles auch zu arbeiten.

Einfacher Test im Editor:
1. Platziere eine der Radaranlagen und achte darauf, dass auch die KI mit Start ist, sprich der Name der Anlage blau bzw. rot hinterlegt ist und nicht gelb, denn sonst ist die Anlage leer.
2. Stelle einen NATO- oder CSAT-Spieler daneben und stelle den als Spieler ein.
3. Wichtigster Punkt: Gib diesem Spieler ein Datalink-fähiges Fahrzeug (Hubschrauber z.B.) und setze den Spieler hinein
4. Schicke im Rücken des Radars einen feindlichen Heli zum Radar.
5. Starte dann die Mission und beobachte, dass das Radar sich von selbst in Richtung des Feindes dreht, sobald es ihn entdeckt und das auch nur wegen dem 120°-Radius. Sobald der auf 360° steht, arbeitet das Radar komplett so, wie es Frozen fordert.

Wenn ich davon ein Video machen würde, dauert das maximal zwei Minuten zum Beweis, dass es genauso arbeitet, wie ich es oben auch schon geschrieben habe. 

>Den Inf detektor habe ich auch nach Stunden suchen in Internet hin bekommen.
Der arbeitet nach Sicht also muss das Radar eine Sichtline dazu haben!
Alles was zwischen dem Radar steht verdeckt dann wieder die anzeige !

Das ist eben ein visueller Sensor, der geht genauso wenig im Dunkeln. Das ist aber nun mal, was Bohemia hergibt, also müssen wir damit arbeiten. Die Visualsensoren funktionieren aber erstaunlich gut, das hatte damals auch die Darter so stark gemacht, sobald es hell war, ist man sofort markiert worden.

**Comment by GNCLORD-MDB** [comment]
Ich bastele da noch mal etwas herum. 
ob man die das Drohnen System doch nehmen kann.

**Comment by GNCLORD-MDB** [comment]
So nun auch ein Radar mit Drohnensystem :-)
Und nun bitte beides drin lassen, damit falls das Drohnen System Problem macht eine alternative da ist.
Probleme im MP mit Drohne habe wir schon zu genügen gehabt.
