### ISSUE TITLE
Nachdem man Leute zieht bleibt man in der Animation stecken!!

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Mission#136]
https://opt4.net/forum/thread/4199-green-hell-schlacht-01-seitenwechsel-feedback/?postID=83515#post83515

https://opt4.net/forum/thread/4199-green-hell-schlacht-01-seitenwechsel-feedback/?postID=83517#post83517

**Comment by GNCLORD-MDB** [comment]
Technisch sollte das nicht möglich sein.

damit wird der Animation check  gestartet 
player addEventHandler ["AnimChanged", {[_this select 0] call FUNC(checkplaymove)}];

hiermit dann gelöscht 
player removeEventHandler ["AnimChanged", 0];

Und dann klapp zuverlässig im Editor.
Würde ja dann heißen das nicht erkannt wir das das ziehen beendet wurde.

**Comment by GNCLORD-MDB** [comment]
Ich habe mal die Irreführende Hint Meldung entfernt.

**Comment by GNCLORD-MDB** [comment]
Ich habe das gestern mal getestet und da gibt es noch eine Bug den ich noch nicht dingfest machen kann. beim erstem mal hat alles geklappt und ich konnte den verletzten ziehen. Dann abgelegt und dann wieder versucht ihn zu ziehen und dann Dings nicht mehr. ich konnte mich nicht bewegen.
Wir wohl auf ein try and error Fehlersuche ankommen wieder.

**Comment by GNCLORD-MDB** [comment]
Ich habe da nun die Animation ausgetauscht so das es nur fehlerfrei gehen sollte.

**Comment by Frozen-byte** [comment]
Der Autowalk kam leider bei manchen nicht so gut an, kann man den irgendwie optional machen?

**Comment by GNCLORD-MDB** [comment]
Ich habe keine andere Möglichkeit gefunden das man das einfrieren der Person verhindern kann.
Das ist der Bug weg und die Funktion des ziehen vollständig vorhanden.

**Comment by gelir95** [comment]
Altes System kann geschlossen werden.
