### ISSUE TITLE
Include Slotlist

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#14]
Stated in document: https://docs.google.com/document/d/11T5YIdsuHJEbMC1mWDSyEcLepk_0QwG8pkOkB6AcXQU/edit#heading=h.lh0lsir3s42t

Please use **exaclty** the wording from the list

**Comment by Frozen-byte** [comment]
If you need any further Information about the restrictions, please let me know.

**Comment by Frozen-byte** [comment]
Note: 
LightAT, HeavyAT, Sniper should spawn without any weapon (they will be included in the Supplyboxes)

**Comment by Frozen-byte** [comment]
BLUFOR:

Alpha | Bravo | Charlie | Delta | HW | LW | Echo
-- | -- | -- | -- | -- | -- | --
1x Gruppenführer | 1x Gruppenführer | 1x Gruppenführer | 1x Gruppenführer | 3x Crew | 3x Piloten | 1x Gruppenführer
1x Sani | 2x Sani | 3x Sani | 2x LMG​ | 1x Ingenieur |   | 1x Crew
1x Light AT | 1x LMG | 1x Grenadier | 1x Grenadier |   |   | 1x Sprengmeister
1x Sniper | 1x Grenadier | 1x Sprengmeister | 1x Sniper​ |   |   | 1x Heavy AT
1x Ingenieur | 1x DMR | 1x Light AT | 1x Spotter​ |   |   | 2x Anti Air
1x Spotter | 1x Sprengmeister | 1x DMR​ |   |   |   | 1x MG

**Comment by GNCLORD-MDB** [comment]
Die Restlichen Slots bis 10 Gruppenstärke mit 6.5 Schützen füllen wieder bei Nato ?

**Comment by Frozen-byte** [comment]
jo

**Comment by GNCLORD-MDB** [comment]
Oppa stellt die Nato Truppen neu zusammen und ändert die Namen.

**Comment by Frozen-byte** [comment]
Die Benennung der Slots ist noch nicht korrekt wie im Dokument vorgegeben

Die Reihenfolge der BLUFOR Squads ist durcheinander. Bitte wie folgt anpassen:
Offiziere
Alpha
Bravo
Charlie
Delta
Echo
Luftwaffe
Panzerwaffe

**Comment by Frozen-byte** [comment]
Die Slotliste ist noch nicht korrekt benannt wie im Dokument vorgegeben:
https://docs.google.com/document/d/11T5YIdsuHJEbMC1mWDSyEcLepk_0QwG8pkOkB6AcXQU/edit#
