### ISSUE TITLE
Falsche Flaggen für die Seiten / Bzw ändern um Seiten unabhänig zu werden.

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Mission#144]
https://opt4.net/forum/thread/4041-neue-m%C3%B6gliche-schlacht-flaggen/

**Comment by gelir95** [comment]
Ist in der Client Mod und muss hier geändert werden: https://github.com/OperationPandoraTrigger/OPT-Client-Mod/tree/master/addons/opt_core/bilder
zudem hab ich damit nichts zu tun.

**Comment by GNCLORD-MDB** [comment]
Den Texturpfad wir doch in der Mission eingetragen, also wird das dann eine Aufgabe für dich sein, das anzupassen, wenn die neuen Flaggenbilder im Clientmod sind oder nicht dirket in die Mission kommen. :-)

**Comment by Frozen-byte** [comment]
Wieso hat dies das Label GAMEBRAKER?
Hindert es uns daran die Mission zu spielen?

**Comment by gelir95** [comment]
Ne weil du einfach die arf_fahne.paa und die sword_fahne.paa austauscht und ich dann nix mehr machen muss.

**Comment by GNCLORD-MDB** [comment]
[WIP]Neue Flaggenbilder #62

**Comment by OPTManu** [comment]
Die Verlinkung passt nicht ganz, aber mit deinem PR https://github.com/OperationPandoraTrigger/OPT-Client-Mod/pull/62 würde das ohnehin nicht funktionieren, da du da die Namen geändert hast und somit nur die alten Flaggen von der Mission gelesen werden. Mit https://github.com/OperationPandoraTrigger/OPT-Client-Mod/pull/64 funktioniert das hingegen, weil die Namen gleichbleiben
