### ISSUE TITLE
datalink kostet bei jedem Aufrüsten erneut Geld

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#150]
Wenn der Datalink bereits ausgerüstet ist, muss er
1. Vorausgewählt sein in der Konfiguration
2. nicht erneut kosten verursachen.

**Comment by GNCLORD-MDB** [comment]
ich muss nur sehen wieso der in **Nachbewaffnen** noch Ausgewählt war.

**Comment by Frozen-byte** [comment]
Ist das geklärt? Ich ereinnere mich an ein Gespräch was du mit den LW hattest, Lord oder muss hier noch was gemacht werden?

**Comment by GNCLORD-MDB** [comment]
ne das sollte erledigt sein, das war wohl ein misverständis das geklärt wurde.
