### ISSUE TITLE
CAS Minigun kosten um 10% senken.

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#153]
Alle Kosten der Minigun für Helikopter sollen um 10% Günstiger werden.

Bodenfahrzeuge sind von dieser Änderung nicht betroffen.

**Comment by GNCLORD-MDB** [comment]
Oki, ich schau mal das ich das bis Donnerstag fertig habe für das training

**Comment by GNCLORD-MDB** [comment]
PR ist drin
