### ISSUE TITLE
change AT-Supply-Boxes

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#16]
https://opt4.net/forum/index.php?thread/3065-mitschriften-der-konzeptsitzungen-2019/&postID=61086#post61086
#### Box 1
1x  MAAWS Mk4 Mod 1 
10x HE 44
10x HEAT 75 
Costs: 200000
#### Box 2
1x PCML
10x HEAT
Costs: 150000
#### Box 3
1x Titan MPRL Compact (no Thermal vision)
10x AT
Costs: 350000
#### Box1
1x RPG-42 Alamut
10x HE TBG-42V
10x HEAT PG-42V
Costs: 200000
#### Box2
1x RPG-7
10x PG-7V
Costs: 150000
#### Box3
1x 9M135 Vorona (no Thermal vision)
10x 9M135 HEAT
Costs: 350000

**Comment by Frozen-byte** [comment]
Boxen nicht kaufbar. Leerfelder in den Menüs.

**Comment by GNCLORD-MDB** [comment]
alter Mod gestartet , auf der CSAT Seite haben die Kisten alle da.
