### ISSUE TITLE
Reparatur funktioniert nicht

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Mission#163]

**Comment by Frozen-byte** [comment]
reopen scheint noch nicht zu gehen https://opt4.net/forum/thread/4386-rosche-1-1-feedback/?postID=87458#post87458

**Comment by GNCLORD-MDB** [comment]
kein Bug nur unkenntis, es fehlt nur noch das Einfügen des Taru Rep Heli in das System. 
Das System als solches geht.
