### ISSUE TITLE
AAF bekommt die Westen die vom Konzeptteam vorgesehen waren (bessere rüstung)

### ISSUE THREAD

**Issue by gelir95** [OperationPandoraTrigger/OPT-Mission#168]

**Comment by gelir95** [comment]
@Frozen-byte 
Kann gemacht werden ich werde die Westen aber nicht nocheinmal tauschen -> Änderung ist Final oder es bearbeitet dannach jemand anderes.

**Comment by Frozen-byte** [comment]
Okay da ich davon ausgehe dass wir sie zurück tauschen wird das wer anders machen wenn du dich nicht dazu herab lässt.

**Comment by gelir95** [comment]
Dann ist die Frage warum machen wir das überhaupt. Das Konzeptteam berät wenn die beratung aber bescheiden ist muss man sie ignorieren / oder halt die entscheidung treffn das es so bleibt. Aber nur mal so zum Testen und um 2 Leuten zu beweisen das sie unrecht haben 20 Minuten mehrarbeit in irgendwas reinstecken....

**Comment by Frozen-byte** [comment]
Weil wir das Konzeptteam nicht bevormunden und ihnen die Chance geben zu zeigen dass wir vielleicht im Unrecht sind.
