### ISSUE TITLE
Es gibt keine Spectator Slots

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Mission#172]

**Comment by GNCLORD-MDB** [comment]
Wieso ist das hier ausgeführt, das ist weder ne Bug noch sonst was. 
Davon ist nichts irgendwo geschrieben das es so was geben soll.

**Comment by gelir95** [comment]
Hat technisch nix mit dem Konzept zu tun und kann unsere EL entscheiden wie sie möchte.
Frage an @Frozen-byte nutzen wir Streamator oder ACE Spectator? 
Out of the box kann Ace 1st person, 3rd person und free cam. Streamator kann halt tolle Kamerafahrten.
