### ISSUE TITLE
Bodentextur von Concrete erzeugt keinen Sound

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Mission#173]
https://opt4.net/forum/thread/4386-rosche-1-1-feedback/?postID=87414#post87414
^-- an Missionmaker vllt melden?

**Comment by gelir95** [comment]
Hab ich mal gemacht.

**Comment by Frozen-byte** [comment]
kannste das Ticket /Kommentar verlinken @gelir95 ?

**Comment by gelir95** [comment]
Siehe WALancer/Rosche#293

**Comment by GNCLORD-MDB** [comment]
geschlossen, da bearbeitet
