### ISSUE TITLE
Mine verschwand aus dem Inventar obwohl sie außerhalb des roten Sperrkreises gelegt wurde.

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#181]
Es wurde versucht sie an den Rand zu legen. Minensperrkreis entsprach nicht der Markierung auf der Karte. 

Entweder Mine zurück ins Inventar legen
Oder Markierung exakt machen
Oder die Möglichkeit nehmen Minen zu legen, sobald man in der Zone ist (ACE Interaktion)

**Comment by gelir95** [comment]
Kann @maxSzone sich mal drann versuchen?

**Comment by GNCLORD-MDB** [comment]
Dazu erst mal bitte klären ob auch der richtige Kreis gemeldet wurde, es gibt zwei Kreise.
einer der von der Fahne und einer des sperrbereiches

**Comment by gelir95** [comment]
Braucht noch immer Bestätigung. Ist so nicht reproduzierbar.

**Comment by GNCLORD-MDB** [comment]
Ich das ein nicht Sprengmeister versucht hat eine Mine zu legen

**Comment by Frozen-byte** [comment]
> Braucht noch immer Bestätigung. Ist so nicht reproduzierbar.


> Ich das ein nicht Sprengmeister versucht hat eine Mine zu legen

Das wurde von Paul gemeldet: https://opt4.net/forum/thread/4498-schlacht-1-feedback/?postID=91963#post91963 ihr könnt ihn einmal um Reproduktion bitten oder es euch von ihm zeigen lassen.

**Comment by GNCLORD-MDB** [comment]
Paul hat als nicht Sprengmeister versucht Minen zu legen das weiß ich

**Comment by gelir95** [comment]
Flaschmeldung, System funktioniert wie gewollt (Sprengmeister können als einzige Minen legen)
