### ISSUE TITLE
Spieler sollen sich auf dem Squadradar sehen. Durch den wegfall der gruppen ist das kaputti gegangen

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#182]

**Comment by gelir95** [comment]
Mehrwert des Squadradars (hat die selbe Funktion wie Minimap Radar)?

**Comment by Frozen-byte** [comment]
Das Squadradar zeigt an:
* Wer gerade spricht (Besondes gut für Neulinge neue die noch nicht alle Stimmen kennen).
* Wo sich die Spieler relativ zueinander befinden, das GPS kann man dann nach norden fixiert lassen und das Squadradar für relative Positionierung nutzen, sehr praktisch.
* keine Mapmarker die ggf. die Position der Mitspieler verdecken oder schwer lesbar machen.

**Comment by GNCLORD-MDB** [comment]
Ja gut dann ales wieder retour und das BIS Gruppensystem wieder rein.
im GPS muss dann der Standard der des Offiziers gesetzt für alle normalen Spieler

**Comment by gelir95** [comment]
Oder alle in eine Gruppe wobei das glaube auch nicht sauber klappt

**Comment by GNCLORD-MDB** [comment]
Zeile 36 in der fn_GPS Funktion, 1gegen 2 austauschen

**Comment by GNCLORD-MDB** [comment]
Fertig umgesetzt

**Comment by Frozen-byte** [comment]
Wo ist der passende PR, der dieses Problem behandelt?

**Comment by Frozen-byte** [comment]
Muss das Ticket leider wieder öffnen. Es funktioniert noch nicht: https://opt4.net/forum/index.php?thread/4533-schlacht-2-feedback/&postID=92765#post92765

**Comment by GNCLORD-MDB** [comment]
Nö, weil nicht die neue Mission genommen wurde. 
So wird auch nie funktionieren wenn nicht die neue Mission nimmt

**Comment by Frozen-byte** [comment]
@gelir95 war die neue Version nicht online?

**Comment by gelir95** [comment]
Nein hatte ich keine Zeit für deshalb gab es auch keinen Changelog ^^
