### ISSUE TITLE
Feindfunk kann abgehört werden

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#183]
Wenn man die gegnerische Funke aufnimmt, kann man jedem zuhören.
Das Gleiche gilt für Fahrzeuge der anderen Fraktion.

Das muss noch verhindert werden (TFAR setting?)

**Comment by GNCLORD-MDB** [comment]
Ich wäre dafür das wenn man ein Funkgerät der Gegenseite aufnimmt das gelöscht wird.

**Comment by Frozen-byte** [comment]
erstmal native Lösungen suchen, sollte es dann nichts geben können wir was selber dazu bauen.

**Comment by GNCLORD-MDB** [comment]
Kann ja wer schon mal die TFAR settings durchschauen

**Comment by Frozen-byte** [comment]
Fahrzeuge müssen auch abgedeckt werden

**Comment by GNCLORD-MDB** [comment]
Ja ist schon drin oder ich weiß wie ich es einbaue
https://github.com/OperationPandoraTrigger/OPT-Server-Mod/blob/733c7c9ef56f0b443df3b53eb4c270852ada1a10/addons/OPT/SHOP/fn_clientInit.sqf#L465

**Comment by GNCLORD-MDB** [comment]
das Artet wieder zu einem Riesen gefummel aus.
Die TFAR setting Einstellung die eigentlich verbieten sollte das man Funkgeräte aufnehmen klappt irgendwie nicht.
Das Funkgerät dann zu löschen, geht auch nicht so wie ich will da ich durch TFAR Besonderheiten es nicht hin bekomme das genau nur das Funkgerät das weg kommt.

Ich wäre erster mal dafür das mach fest gelegt das man keine Funkgeräte aufnehmen darf.

**Comment by GNCLORD-MDB** [comment]
geschlossen, da bearbeitet
