### ISSUE TITLE
NATO Charlie Sanitäter spawnt ohne Kompass 

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Mission#25]

**Comment by GNCLORD-MDB** [comment]
Ich kann keinen Sani finden, der keinen Kompass hat.  
Oder der nach Respwan keinen mehr hat.

**Comment by GNCLORD-MDB** [comment]
Alle Sani haben eine Kompass und nach dem Respwan war der immer noch dar.

Allerdings habe ich eine Warn- / Fehlermeldung vom ACE Gearsave gesehen. 

> 17:27:45 Error in expression <lTo ACE_player) then {
> private _items = ace_common_uniqueItemsCache;
> if (isNil ">
> 17:27:45   Error position: <ace_common_uniqueItemsCache;
> if (isNil ">
> 17:27:45   Error Nicht definierte Variable in Ausdruck: ace_common_uniqueitemscache
> 17:27:45 File z\ace\addons\common\functions\fnc_uniqueItems.sqf, line 31

**Comment by senshi-x** [comment]
Ist das gefixt, @GNCLORD-MDB ?

**Comment by GNCLORD-MDB** [comment]
da gab nicht zu fixsen

**Comment by senshi-x** [comment]
Noch besser, dann schließe ich das Issue einfach so :) .
