### ISSUE TITLE
Script Fehlermeldung wegen CLIB Eintrag

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Mission#26]
Script Fehlermeldung von Revive System wegen CLIB Eintrag

]Script Fehlermeldung von Shop System wegen CLIB Eintrag.

**Comment by GNCLORD-MDB** [comment]
die Einträge verursachen Warn- und Fehlermeldungen ,da das Clib Script nicht laufen.

> 
> 17:17:03 Error in expression <"OPTRemoveMarkerTextRevive",_unit] call CLib_fnc_globalEvent;
> 
> if (dialog) then >
> 17:17:03   Error position: <CLib_fnc_globalEvent;
> 
> if (dialog) then >
> 17:17:03   Error Nicht definierte Variable in Ausdruck: clib_fnc_globalevent

**Comment by GNCLORD-MDB** [comment]
Einträge abgestellt bis wir es nutzen

**Comment by senshi-x** [comment]
Fixed with #30
