### ISSUE TITLE
Schreiben im Chat trotz Bewusstlosigkeit

### ISSUE THREAD

**Issue by OPTManu** [OperationPandoraTrigger/OPT-Mission#31]
Aktuell ist der Chat in der Bewusstlosigkeit nutzbar, obwohl sogar die Meldung erscheint, dass der Chat blockiert wäre. Getestet mit aktuellen Mods und aktuellem Legacy-Build auf einem lokalen Dedi-Server, ist mir aber auch schon bei Prolog 1 aufgefallen.
[https://www.youtube.com/watch?v=8vVcbAuMlbs](https://www.youtube.com/watch?v=8vVcbAuMlbs)

**Comment by senshi-x** [comment]
Ist es nicht sinnbefreit, wenn der Chat deaktiviert ist? Die Leute können ja nach wie vor eh im TS reden.

Also Frage nach dem Soll-Zustand. Und definitiv lowest-prio :D .

**Comment by OPTManu** [comment]
Soll-Zustand war, dass man schon mit den Leuten direkt reden kann, aber eben nicht direkt schreiben oder Funkgeräte benutzen.
Man soll schon noch mit Leuten reden können, die es bis zur Leiche geschafft haben, aber es soll vermieden werden, dass direkt nach Umfallen Infos weitergegeben werden, die den Auslöser der Bewusstlosigkeit betreffen, darum wurden Chat und Funkgeräte blockiert.

**Comment by senshi-x** [comment]
Ah, Funkgeräte auch blockiert, dann wird ein Schuh draus. Ja, daran kann ich mich auch noch erinnern, jetzt wo du es sagst.
Ist also Todo, aber ehrlich gesagt würde ich es nicht wichtig genug einordnen, um da jetzt in der legacy Fehlersuche zu betreiben, außer Lord oder jemand weiß genau, wo das Prob herkommt.

**Comment by Frozen-byte** [comment]
Ist das hier noch aktuell?

**Comment by GNCLORD-MDB** [comment]
Auf den Trainserver getestet, chat geht nicht bei Bewustlosigkeit. kann geschlossen werden.

**Comment by OPTManu** [comment]
Stimmt so nicht ganz, habe es ebenso getestet und selbes Verhalten wie oben im Video, jetzt bin ich aber auch darauf gekommen, warum. 
Das Script blockiert nur die Default-Taste, aber nicht alle anderen. Nachdem ich den Chat seit meinem zweiten Tag in ArmA 3 auf einer anderen Taste habe, ist mir das auch nicht früher aufgefallen. Ich schaue mir mal an, wie man das Script umschreiben kann, dass es den Chat ganz sperrt und nicht nur eine einzelne Taste

**Comment by Frozen-byte** [comment]
Dann habe ich das Issue wieder geöffnet. und wir waren auf einen MR :=)

**Comment by gelir95** [comment]
Sollte im aktuellen System alles funktionieren.

**Comment by Frozen-byte** [comment]
Habe es nicht reproduzieren können und bisher keine weitere Meldung vernommen. Dann close ich es.
