### ISSUE TITLE
Datalink cost each time when changing phylons

### ISSUE THREAD

**Issue by oldLucke** [OperationPandoraTrigger/OPT-Mission#66]
When  you change the phylon layout of a vehicle and even use the same loadoutyou still have to pay 10k for the datalink each time. ![used empty loadout](https://i.imgur.com/o6WM2eI.png) ![still have to pay 10k](https://i.imgur.com/mbDj4xw.png)

**Comment by GNCLORD-MDB** [comment]
Das ist so richtig, da es keine Feststellung gab zu ermitteln ob ein Fahrzeug data link hat.
Die 10.000 sind ein sehr kleiner Betrag.
man könnte prüfen ob es eine Möglichkeit inzwischen gibt das festzustellen ob ein Fahrzeug schon data link hat.
Sonst müsste man das System erweitern, das man festhalten kann ob das bei einem Fahrzeug gekauft wurde

**Comment by Frozen-byte** [comment]
Es ist NICHT gewollt, dass die 10000 jedes mal neu bezahlt werden.

Lass den DataLink per Default einfach draußen?

**Comment by GNCLORD-MDB** [comment]
Könnte man machen, dann muss nur entsprechend eingestellt werden das man per Hand datalink auswählen muss

**Comment by senshi-x** [comment]
Je nachdem, wie du es implementiert hast, gibt es für jedes Teilfeature von Datalink ein "get":
https://community.bistudio.com/wiki/vehicleReceiveRemoteTargets
https://community.bistudio.com/wiki/vehicleReportOwnPosition
https://community.bistudio.com/wiki/vehicleReportRemoteTargets

Die dazugehörigen setter heißen gleich, nur mit einem "set" davor.

**Comment by GNCLORD-MDB** [comment]
Mh, muss ich schauen ob über einen kleinen Umweg ich feststellen kann ob datalink vorhanden ist

**Comment by Yayshan** [comment]
@GNCLORD-MDB Wie ist hier der Stand?

**Comment by GNCLORD-MDB** [comment]
alt und nicht relevant

**Comment by Frozen-byte** [comment]
Wieso nicht mehr relevant?
Wo wurde es gefixt?

**Comment by GNCLORD-MDB** [comment]
Wie haben die ganze letzte Kampage so gespielt. 
Und eine Möglichkeit abzufragen ob einer Datalink gekauft hat gibt immer noch nicht.
Ich müsste da was entwickeln wie man Feststellen kann ob ein Fahrzeug Datalink hat.  
Das war deshalb nie mehr das Thema, das das unbedingt gelöst werden muss.

**Comment by Frozen-byte** [comment]
Es bleibt relevant! Nur weil ein Fehler 10 Monate alt ist, heißt es nicht, dass er nicht mehr relevant ist.

Dieses Topic erwartet noch einen PR der ihn behebt.

**Comment by Frozen-byte** [comment]
Weiter geht es hier https://github.com/OperationPandoraTrigger/OPT-Client-Mod/issues/59
