### ISSUE TITLE
unnecessary forced view distanc settings

### ISSUE THREAD

**Issue by oldLucke** [OperationPandoraTrigger/OPT-Mission#67]
Pls don't force the settings 2-4. If you want to restrict the total view distance forcing setting 5 does the trick. 
![vied distance settings](https://i.imgur.com/UW1zBzF.png)

**Comment by Frozen-byte** [comment]
Übersetzung: Die Option 2, 3 und 4 soll die Mission nicht überschreiben.
Option5 limitiert die maximale Sichtweite, die anderen soll der Client sich frei einstellen können.

**Comment by senshi-x** [comment]
Fixed with #71
