### ISSUE TITLE
Add Cyrus and MAR10 weapons

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#8]
Add Cyrus and MAR10 weapons with ammo to Special-Purpose-Containers.
Those weapons are only allowed by sniper slots.

**Comment by GNCLORD-MDB** [comment]
Falsch hier gehört zum Mod Repro

**Comment by GNCLORD-MDB** [comment]
eingebaut und erledigt

**Comment by Frozen-byte** [comment]
Danke hier nochmal das richtige Issue: https://github.com/OperationPandoraTrigger/OPT-Server-Mod/issues/35
