### ISSUE TITLE
Ifrit HMG spawned mit 500 Schuss und lässt sich nicht bewaffnen

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#97]

**Comment by OPTManu** [comment]
Wie ist hier der Status?

**Comment by GNCLORD-MDB** [comment]
fertig, ist in der Mission schon langs gefixt durch mir und @oppa-schneutzel  
Steht doch in Bugtracker das das fertig ist.

**Comment by OPTManu** [comment]
Frozen und Yoshi wussten gerade nicht, dass das gefixt wäre, deswegen frage ich.
In welchem Bugtracker steht das?

**Comment by GNCLORD-MDB** [comment]
in den den @Frozen-byte extra selber aufgemacht hat. 
https://github.com/orgs/OperationPandoraTrigger/projects/3

**Comment by OPTManu** [comment]
Den meinst du, ok.
