### ISSUE TITLE
Wracks bleiben auf Brücken liegen

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Mission#99]
sollen nach 5 Minuten verschwinden

**Comment by GNCLORD-MDB** [comment]
> Brücken Aufräumfunktion für die Brücken was Wracks löscht auf der Brücke.
> 
> fnc_handledeadvehicle.sqf
> 
> In die Datei. die Trigger eintragen, die man für jede Brücke platzieren muss, opt_garbage_collector_bridges_xyz.
> 

Sobald Oppa dies gemacht ist das fertig.
